services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: my-streaming-time-api
    ports:
      - "3000:3000" 
    env_file:
      - .env.docker
    depends_on:
      - mongodb
    volumes:
      - /usr/src/app/node_modules
      - /usr/src/app/dist
      - .:/usr/src/app


  mongodb:
    image: mongo
    container_name: my-streaming-time-db-2
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
