FROM node:22-alpine

WORKDIR /usr/src/app

COPY package*.json ./ 

RUN npm install

RUN npm install -g typescript

COPY . .

RUN npm run build

RUN ls -la dist/

EXPOSE 3000

CMD ["npm", "dev:docker"]