name: Weekly Cover Update

on:
  schedule:
    - cron: '0 12 * * 0'  # Todos os domingos às 12h UTC (09h de Brasília)
  workflow_dispatch:       # Permite execução manual

jobs:
  call-cover-update:
    runs-on: ubuntu-latest

    steps:
      - name: Wake up server via /health
        run: |
          for i in {1..5}; do
            echo "Checking health (attempt $i)..."
            code=$(curl -s -o /dev/null -w "%{http_code}" "$HEALTH_CHECK_URL")
            if [ "$code" = "200" ]; then
              echo "Server is up!"
              break
            fi
            echo "Still sleeping... waiting 15s"
            sleep 15
          done
        env:
          HEALTH_CHECK_URL: ${{ secrets.HEALTH_CHECK_URL }}

      - name: Call /streamingTypes/change-cover
        run: |
          echo "Calling $COVER_UPDATE_API_URL"
          curl -X GET "$COVER_UPDATE_API_URL" \
            -H "Authorization: $COVER_UPDATE_TOKEN" \
            -H "Content-Type: application/json"
        env:
          COVER_UPDATE_API_URL: ${{ secrets.COVER_UPDATE_API_URL }}
          COVER_UPDATE_TOKEN: ${{ secrets.COVER_UPDATE_TOKEN }}
